### ISSUE TITLE
i know absolutely nothing.

### ISSUE THREAD

**Issue by ALinuxLover** [gitscratch/gitscratch#16]
Hello, i know this makes me sound like I know nothing at all but...

1. is the electron app runnable (is that a word) (asking bc idk if it works yet)
2. if so, how do you do it? :P im so sorry

**Comment by ALinuxLover** [comment]
omg nevermind i am not smart
see this is why i need sleep xD

**Comment by Blaze349** [comment]
#Info

We are building two things it seems. A website and database for users and an app that they can download and run.

**Comment by Blaze349** [comment]
Found the original question in my emails.
>* is the electron app runnable (is that a word) (asking bc idk if it works yet)
>* if so, how do you do it? :P im so sorry

It isn't yet but when it is you can type
`    npm start`
Or
`    electron .`
