### ISSUE TITLE
Will there be version control?

### ISSUE THREAD

**Issue by ALinuxLover** [gitscratch/gitscratch#31]
If there will be version control (like normal git...) maybe it should be mentioned on the homepage?

**Comment by Blaze349** [comment]
Git is version control

**Comment by ALinuxLover** [comment]
I know
That's the point lol

**Comment by Blaze349** [comment]
Yeah there will be version control. Do you know about the app branch?

**Comment by card100** [comment]
Yes, version control is the main part of Git.  That is one of the main goals of GitScratch
