### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vutondesign** [gitscratch/gitscratch#38]
I've got a quick question - The "sign up" button doesn't work, is this because this is still in development?

**Comment by redmangospros** [comment]
this is longer in develpooment, it's ded. https://gitter.im/gitscratch-/Lobby

**Comment by vutondesign** [comment]
Ah okay

**Comment by redmangospros** [comment]
Your welcome, hey want to work on something together plz?

**Comment by vutondesign** [comment]
What would that thing be?

**Comment by redmangospros** [comment]
?

**Comment by vutondesign** [comment]
What would we be working on?

**Comment by redmangospros** [comment]
anything.

**Comment by redmangospros** [comment]
a website company? you css and me html for free? a css framework? chrome extestion?

**Comment by redmangospros** [comment]
hi

**Comment by vutondesign** [comment]
If it was a website company, I wouldn't be working for free. I've also already made a css framework and chrome extension.

- https://github.com/vutondesign/SimplePick
- https://github.com/vutondesign/bronze

**Comment by redmangospros** [comment]
well, lets make anotnher extestion

**Comment by vutondesign** [comment]
Ideas?
