### ISSUE TITLE
Are we not going to have a website

### ISSUE THREAD

**Issue by card100** [gitscratch/gitscratch#9]
Should we have a website that people can directly connect to?  It would seem more practical for some people.

**Comment by Blaze349** [comment]
I think we should. Unless we are planning on making a framwork

**Comment by card100** [comment]
Ok
What happened to index.html (and the other .html files)

**Comment by Blaze349** [comment]
I moved them to the views folder and renamed them with a .ejs extension.
Have you tried running the server? What do you think of my changes?

**Comment by card100** [comment]
Ah that's why I can't find them

**Comment by card100** [comment]
Why .ejs?

**Comment by Blaze349** [comment]
EJS stands for embedded JS. It allows us to create a dynamic website so that rather than making a html page for each user profile or project page we can just have one and fill in the details when they are requested.

Here are some guides:
http://www.embeddedjs.com/
https://coligo.io/templating-node-and-express-apps-with-ejs/

We could use any templating engine you want though.

**Comment by card100** [comment]
My only problem is that web browsers don't like it.

**Comment by Blaze349** [comment]
Like ejs? EJS is compiled into html which the browser can see. The browser can't read ejs itself

**Comment by card100** [comment]
It doesn't like the file extention

**Comment by Blaze349** [comment]
I'll change it

**Comment by card100** [comment]
:+1:

**Comment by ALinuxLover** [comment]
I know I'm not part of this but I think you should--what about Windows?

**Comment by Blaze349** [comment]
Yeah. But I'm in Jerusalem right now.
@card100 Are we going to have an app or a web app. An app doesn't require hosting money

**Comment by card100** [comment]
Is it possible to do both?
I can take care of hosting money and we could use Electron.atom.io for an app framework?

I can take care of changing the extensions to .html.

Have a nice trip in Jerusalem

**Comment by Blaze349** [comment]
The idea that herohamp had is that we could use github pages as a landing page for downloading the electron.io app.

We could do both if you want.

Thanks, I've changed the files now
